---
title: Retrium Dev Blog
email: customerlove@retrium.com
author: retrium
author_github: retrium
description: |
  Adventures in life and web development at Retrium
baseurl: "/"
url: https://retrium.github.io/
paginate: 12
github:
  user: retrium
  repository: retrium.github.io
  url: https://retrium.github.io
  status: false
home_bgfile: bg.jpg
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
- jekyll-paginate
exclude:
- vendor
